
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wagis
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    int turn =2;
    int buttonused[]={0,0,0,0,0,0,0,0,0};
    int pXwon[]={0,0,0,0,0,0,0,0,0};
    int pOwon[]={0,0,0,0,0,0,0,0,0};
    
    
  int pXwon()
  {
              if(pXwon[0]==1 && pXwon[1]==1 && pXwon[2]==1){
                  return 1;
              }
              if(pXwon[3]==1 && pXwon[4]==1 && pXwon[5]==1){
                  return 1;
              }
              if(pXwon[6]==1 && pXwon[7]==1 && pXwon[8]==1){
                  return 1;
              }
              if(pXwon[0]==1 && pXwon[3]==1 && pXwon[6]==1){
                  return 1;
              }
              if(pXwon[1]==1 && pXwon[4]==1 && pXwon[7]==1){
                  return 1;
              }
              if(pXwon[2]==1 && pXwon[5]==1 && pXwon[8]==1){
                  return 1;
              }
              if(pXwon[0]==1 && pXwon[4]==1 && pXwon[8]==1){
                  return 1;
              }
              if(pXwon[2]==1 && pXwon[4]==1 && pXwon[6]==1){
                  return 1;
              }
        return 0;
  }
          
int pOwon ()
          {
              if(pOwon[0]==1 && pOwon[1]==1 && pOwon[2]==1){
                  return 1;
              }
              if(pOwon[3]==1 && pOwon[4]==1 && pOwon[5]==1){
                  return 1;
              }
              if(pOwon[6]==1 && pOwon[7]==1 && pOwon[8]==1){
                  return 1;
              }
              if(pOwon[0]==1 && pOwon[3]==1 && pOwon[6]==1){
                  return 1;
              }
              if(pOwon[1]==1 && pOwon[4]==1 && pOwon[7]==1){
                  return 1;
              }
              if(pOwon[2]==1 && pOwon[5]==1 && pOwon[8]==1){
                  return 1;
              }
              if(pOwon[0]==1 && pOwon[4]==1 && pOwon[8]==1){
                  return 1;
              }
              if(pOwon[2]==1 && pOwon[4]==1 && pOwon[6]==1){
                  return 1;
              }                   
        return 0;
               
          }          
          
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("TIC TAC TOE");

        B1.setBackground(new java.awt.Color(0, 0, 0));
        B1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        B1.setForeground(new java.awt.Color(255, 204, 204));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(0, 0, 0));
        B2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        B2.setForeground(new java.awt.Color(255, 204, 204));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(0, 0, 0));
        B3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        B3.setForeground(new java.awt.Color(255, 204, 204));
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(0, 0, 0));
        B4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        B4.setForeground(new java.awt.Color(255, 204, 204));
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(0, 0, 0));
        B5.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        B5.setForeground(new java.awt.Color(255, 204, 204));
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(0, 0, 0));
        B6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        B6.setForeground(new java.awt.Color(255, 204, 204));
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        B7.setBackground(new java.awt.Color(0, 0, 0));
        B7.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        B7.setForeground(new java.awt.Color(255, 204, 204));
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B8.setBackground(new java.awt.Color(0, 0, 0));
        B8.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        B8.setForeground(new java.awt.Color(255, 204, 204));
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(0, 0, 0));
        B9.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        B9.setForeground(new java.awt.Color(255, 204, 204));
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B8, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(B3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(B2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        if(buttonused[0]==0)
        {  
        if(turn%2==0)
        {
            turn++;
            B1.setText("X");
            buttonused[0]=1;
            pXwon[0]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
                
        }
        else
        {
            turn++;
            B1.setText("O");
            buttonused[0]=1;
            pOwon[0]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
            
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS USED");
                }

    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        if(buttonused[1]==0)
        {  
        if(turn%2==0)
        {
            turn++;
            B2.setText("X");
            buttonused[1]=1;
            pXwon[1]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
                
        }
        else
        {
            turn++;
            B2.setText("O");
            buttonused[1]=1;
            pOwon[1]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
            
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS USED");
                }
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        if(buttonused[2]==0)
        {  
        if(turn%2==0)
        {
            turn++;
            B3.setText("X");
            buttonused[2]=1;
            pXwon[2]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
                
        }
        else
        {
            turn++;
            B3.setText("O");
            buttonused[2]=1;
            pOwon[2]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
            
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS USED");
                }
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        if(buttonused[3]==0)
        {  
        if(turn%2==0)
        {
            turn++;
            B4.setText("X");
            buttonused[3]=1;
            pXwon[3]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
                
        }
        else
        {
            turn++;
            B4.setText("O");
            buttonused[3]=1;
            pOwon[3]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
            
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS USED");
                }
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        if(buttonused[4]==0)
        {  
        if(turn%2==0)
        {
            turn++;
            B5.setText("X");
            buttonused[4]=1;
            pXwon[4]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
                
        }
        else
        {
            turn++;
            B5.setText("O");
            buttonused[4]=1;
            pOwon[4]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
            
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS USED");
                }
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        if(buttonused[5]==0)
        {  
        if(turn%2==0)
        {
            turn++;
            B6.setText("X");
            buttonused[5]=1;
            pXwon[5]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
                
        }
        else
        {
            turn++;
            B6.setText("O");
            buttonused[5]=1;
            pOwon[5]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
            
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS USED");
                }
    }//GEN-LAST:event_B6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
        if(buttonused[6]==0)
        {  
        if(turn%2==0)
        {
            turn++;
            B7.setText("X");
            buttonused[6]=1;
            pXwon[6]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
                
        }
        else
        {
            turn++;
            B7.setText("O");
            buttonused[6]=1;
            pOwon[6]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
            
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS USED");
                }
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
        if(buttonused[7]==0)
        {  
        if(turn%2==0)
        {
            turn++;
            B8.setText("X");
            buttonused[7]=1;
            pXwon[7]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
                
        }
        else
        {
            turn++;
            B8.setText("O");
            buttonused[7]=1;
            pOwon[7]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
            
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS USED");
                }
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
        if(buttonused[8]==0)
        {  
        if(turn%2==0)
        {
            turn++;
            B9.setText("X");
            buttonused[8]=1;
            pXwon[8]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
                
        }
        else
        {
            turn++;
            B9.setText("O");
            buttonused[8]=1;
            pOwon[8]=1;
            
            int resultt1=pXwon();
            int resultt2=pOwon();
           
            if(resultt1==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Player X wins the game!");
            }
            else if(resultt2 == 1)
                {
                JOptionPane.showMessageDialog(rootPane, "Player O wins the game!");
            }
            
        }
        }
        else{
                JOptionPane.showMessageDialog(rootPane, "THIS BUTTON IS USED");
                }
    }//GEN-LAST:event_B9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        B1.setText("");
        B2.setText("");
        B3.setText("");
        B4.setText("");
        B5.setText("");
        B6.setText("");
        B7.setText("");
        B8.setText("");
        B9.setText("");
        
        turn=2;
        for(int i=0; i<9; i++)
        {
            buttonused[i]=0;
        }
        turn=2;
        for(int i=0; i<9; i++)
        {
            pXwon[i]=0;
        }
        turn=2;
        for(int i=0; i<9; i++)
        {
            pOwon[i]=0;
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
